### 전략 구현하기

In [2]:
# 필수 라이브러리 설치
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
# 데이터 가져오기
fs_path = r'E:\jupyter\Quant with Python\Excel_data\재무제표데이터.xlsx'
pd.read_excel(fs_path)

,Unnamed: 0,2012/02,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,2013/02,Unnamed: 9,...,Unnamed: 264,Unnamed: 265,Unnamed: 266,2020/11,Unnamed: 268,Unnamed: 269,Unnamed: 270,Unnamed: 271,Unnamed: 272,Unnamed: 273
0,NaN,당기순이익,매출액,부채,영업이익,영업활동으로인한현금흐름,자본,자산,당기순이익,매출액,...,영업활동으로인한현금흐름,자본,자산,당기순이익,매출액,부채,영업이익,영업활동으로인한현금흐름,자본,자산
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A098120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A131100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A009520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2288,A010240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2289,A189980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2290,A003280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2291,A037440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2292,A238490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# 가져온 데이터 칼럼 수정
# 이전에 만들어놨던거처럼 만들기 위함
raw_data = pd.read_excel(fs_path,)
big_col = list(raw_data.columns)
small_col = list(raw_data.iloc[0])

In [5]:
big_col

['Unnamed: 0',
 '2012/02',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 '2013/02',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 '2014/02',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 '2014/08',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 '2017/06',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Unnamed: 34',
 'Unnamed: 35',
 '2017/09',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 'Unnamed: 42',
 '2017/11',
 'Unnamed: 44',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 48',
 'Unnamed: 49',
 '2017/12',
 'Unnamed: 51',
 'Unnamed: 52',
 'Unnamed: 53',
 'Unnamed: 54',
 'Unnamed: 55',
 'Unnamed: 56',
 '2018/02',
 'Unnamed: 58',
 'Unnamed: 59',
 'Unnamed: 60',
 'Unnamed: 61',
 'Unnamed: 62',
 'Unnamed: 63',
 '2018/03',
 'Unnamed: 65',
 'Unnamed: 66',
 'Unnamed: 67',
 'Unnamed: 68',
 'Unnamed: 69',
 'Unnamed: 70',
 '2018/05',
 'Unnamed: 72',
 'Unnamed: 73',
 'Unnamed: 74',
 'Unnamed: 75',
 'Unnamed: 76',
 'Unnamed: 77',
 '2018/06',
 'Unnamed: 79',
 'Unnamed: 80',
 'Unnamed: 81',
 'Unnamed: 82',
 'Unnamed: 83',
 'Unnamed: 84',
 '2018/07',
 'Unnamed: 86',
 'Unnamed: 87',
 'Unnamed: 88',
 'Unnamed: 89',
 'Unnamed: 90',
 'Unnamed: 91',
 '2018/08',
 'Unnamed: 93',
 'Unnamed: 94',
 'Unnamed: 95',
 'Unnamed: 96',
 'Unnamed: 97',
 'Unnamed: 98',
 '2018/09',
 'Unnamed: 100',
 'Unnamed: 101',
 'Unnamed: 102',
 'Unnamed: 103',
 'Unnamed: 104',
 'Unnamed: 105',
 '2018/10',
 'Unnamed: 107',
 'Unnamed: 108',
 'Unnamed: 109',
 'Unnamed: 110',
 'Unnamed: 111',
 'Unnamed: 112',
 '2018/11',
 'Unnamed: 114',
 'Unnamed: 115',
 'Unnamed: 116',
 'Unnamed: 117',
 'Unnamed: 118',
 'Unnamed: 119',
 '2018/12',
 'Unnamed: 121',
 'Unnamed: 122',
 'Unnamed: 123',
 'Unnamed: 124',
 'Unnamed: 125',
 'Unnamed: 126',
 '2019/01',
 'Unnamed: 128',
 'Unnamed: 129',
 'Unnamed: 130',
 'Unnamed: 131',
 'Unnamed: 132',
 'Unnamed: 133',
 '2019/02',
 'Unnamed: 135',
 'Unnamed: 136',
 'Unnamed: 137',
 'Unnamed: 138',
 'Unnamed: 139',
 'Unnamed: 140',
 '2019/03',
 'Unnamed: 142',
 'Unnamed: 143',
 'Unnamed: 144',
 'Unnamed: 145',
 'Unnamed: 146',
 'Unnamed: 147',
 '2019/05',
 'Unnamed: 149',
 'Unnamed: 150',
 'Unnamed: 151',
 'Unnamed: 152',
 'Unnamed: 153',
 'Unnamed: 154',
 '2019/06',
 'Unnamed: 156',
 'Unnamed: 157',
 'Unnamed: 158',
 'Unnamed: 159',
 'Unnamed: 160',
 'Unnamed: 161',
 '2019/07',
 'Unnamed: 163',
 'Unnamed: 164',
 'Unnamed: 165',
 'Unnamed: 166',
 'Unnamed: 167',
 'Unnamed: 168',
 '2019/08',
 'Unnamed: 170',
 'Unnamed: 171',
 'Unnamed: 172',
 'Unnamed: 173',
 'Unnamed: 174',
 'Unnamed: 175',
 '2019/09',
 'Unnamed: 177',
 'Unnamed: 178',
 'Unnamed: 179',
 'Unnamed: 180',
 'Unnamed: 181',
 'Unnamed: 182',
 '2019/10',
 'Unnamed: 184',
 'Unnamed: 185',
 'Unnamed: 186',
 'Unnamed: 187',
 'Unnamed: 188',
 'Unnamed: 189',
 '2019/11',
 'Unnamed: 191',
 'Unnamed: 192',
 'Unnamed: 193',
 'Unnamed: 194',
 'Unnamed: 195',
 'Unnamed: 196',
 '2019/12',
 'Unnamed: 198',
 'Unnamed: 199',
 'Unnamed: 200',
 'Unnamed: 201',
 'Unnamed: 202',
 'Unnamed: 203',
 '2020/01',
 'Unnamed: 205',
 'Unnamed: 206',
 'Unnamed: 207',
 'Unnamed: 208',
 'Unnamed: 209',
 'Unnamed: 210',
 '2020/02',
 'Unnamed: 212',
 'Unnamed: 213',
 'Unnamed: 214',
 'Unnamed: 215',
 'Unnamed: 216',
 'Unnamed: 217',
 '2020/03',
 'Unnamed: 219',
 'Unnamed: 220',
 'Unnamed: 221',
 'Unnamed: 222',
 'Unnamed: 223',
 'Unnamed: 224',
 '2020/05',
 'Unnamed: 226',
 'Unnamed: 227',
 'Unnamed: 228',
 'Unnamed: 229',
 'Unnamed: 230',
 'Unnamed: 231',
 '2020/06',
 'Unnamed: 233',
 'Unnamed: 234',
 'Unnamed: 235',
 'Unnamed: 236',
 'Unnamed: 237',
 'Unnamed: 238',
 '2020/07',
 'Unnamed: 240',
 'Unnamed: 241',
 'Unnamed: 242',
 'Unnamed: 243',
 'Unnamed: 244',
 'Unnamed: 245',
 '2020/08',
 'Unnamed: 247',
 'Unnamed: 248',
 'Unnamed: 249',
 'Unnamed: 250',
 'Unnamed: 251',
 'Unnamed: 252',
 '2020/09',
 'Unnamed: 254',
 'Unnamed: 255',
 'Unnamed: 256',
 'Unnamed: 257',
 'Unnamed: 258',
 'Unnamed: 259',
 '2020/10',
 'Unnamed: 261',
 'Unnamed: 262',
 'Unnamed: 263',
 'Unnamed: 264',
 'Unnamed: 265',
 'Unnamed: 266',
 '2020/11',
 'Unnamed: 268',
 'Unnamed: 269',
 'Unnamed: 270',
 'Unnamed: 271',
 'Unnamed: 272',
 'Unnamed: 273']

In [6]:
small_col

[nan,
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산',
 '당기순이익',
 '매출액',
 '부채',
 '영업이익',
 '영업활동으로인한현금흐름',
 '자본',
 '자산']

In [11]:
# big_col 개선
new_big_col = []
for num,col in enumerate(big_col):
    if 'Unnamed' in col:
        new_big_col.append(big_col[num-1])
    else:
        new_big_col.append(big_col[num])

In [12]:
new_big_col # 다시 해야할 듯....

['Unnamed: 273',
 '2012/02',
 '2012/02',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 '2013/02',
 '2013/02',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 '2014/02',
 '2014/02',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 '2014/08',
 '2014/08',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 '2017/06',
 '2017/06',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Unnamed: 34',
 '2017/09',
 '2017/09',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 '2017/11',
 '2017/11',
 'Unnamed: 44',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 48',
 '2017/12',
 '2017/12',
 'Unnamed: 51',
 'Unnamed: 52',
 'Unnamed: 53',
 'Unnamed: 54',
 'Unnamed: 55',
 '2018/02',
 '2018/02',
 'Unnamed: 58',
 'Unnamed: 59',
 'Unnamed: 60',
 'Unnamed: 61',
 'Unnamed: 62',
 '2018/03',
 '2018/03',
 'Unnamed: 65',
 'Unnamed: 66',
 'Unnamed: 67',
 'Unnamed: 68',
 'Unnamed: 69',
 '2018/05',
 '2018/05',
 'Unnamed: 72',
 'Unnamed: 73',
 'Unnamed: 74',
 'Unnamed: 75',
 'Unnamed: 76',
 '2018/06',
 '2018/06',
 'Unnamed: 79',
 'Unnamed: 80',
 'Unnamed: 81',
 'Unnamed: 82',
 'Unnamed: 83',
 '2018/07',
 '2018/07',
 'Unnamed: 86',
 'Unnamed: 87',
 'Unnamed: 88',
 'Unnamed: 89',
 'Unnamed: 90',
 '2018/08',
 '2018/08',
 'Unnamed: 93',
 'Unnamed: 94',
 'Unnamed: 95',
 'Unnamed: 96',
 'Unnamed: 97',
 '2018/09',
 '2018/09',
 'Unnamed: 100',
 'Unnamed: 101',
 'Unnamed: 102',
 'Unnamed: 103',
 'Unnamed: 104',
 '2018/10',
 '2018/10',
 'Unnamed: 107',
 'Unnamed: 108',
 'Unnamed: 109',
 'Unnamed: 110',
 'Unnamed: 111',
 '2018/11',
 '2018/11',
 'Unnamed: 114',
 'Unnamed: 115',
 'Unnamed: 116',
 'Unnamed: 117',
 'Unnamed: 118',
 '2018/12',
 '2018/12',
 'Unnamed: 121',
 'Unnamed: 122',
 'Unnamed: 123',
 'Unnamed: 124',
 'Unnamed: 125',
 '2019/01',
 '2019/01',
 'Unnamed: 128',
 'Unnamed: 129',
 'Unnamed: 130',
 'Unnamed: 131',
 'Unnamed: 132',
 '2019/02',
 '2019/02',
 'Unnamed: 135',
 'Unnamed: 136',
 'Unnamed: 137',
 'Unnamed: 138',
 'Unnamed: 139',
 '2019/03',
 '2019/03',
 'Unnamed: 142',
 'Unnamed: 143',
 'Unnamed: 144',
 'Unnamed: 145',
 'Unnamed: 146',
 '2019/05',
 '2019/05',
 'Unnamed: 149',
 'Unnamed: 150',
 'Unnamed: 151',
 'Unnamed: 152',
 'Unnamed: 153',
 '2019/06',
 '2019/06',
 'Unnamed: 156',
 'Unnamed: 157',
 'Unnamed: 158',
 'Unnamed: 159',
 'Unnamed: 160',
 '2019/07',
 '2019/07',
 'Unnamed: 163',
 'Unnamed: 164',
 'Unnamed: 165',
 'Unnamed: 166',
 'Unnamed: 167',
 '2019/08',
 '2019/08',
 'Unnamed: 170',
 'Unnamed: 171',
 'Unnamed: 172',
 'Unnamed: 173',
 'Unnamed: 174',
 '2019/09',
 '2019/09',
 'Unnamed: 177',
 'Unnamed: 178',
 'Unnamed: 179',
 'Unnamed: 180',
 'Unnamed: 181',
 '2019/10',
 '2019/10',
 'Unnamed: 184',
 'Unnamed: 185',
 'Unnamed: 186',
 'Unnamed: 187',
 'Unnamed: 188',
 '2019/11',
 '2019/11',
 'Unnamed: 191',
 'Unnamed: 192',
 'Unnamed: 193',
 'Unnamed: 194',
 'Unnamed: 195',
 '2019/12',
 '2019/12',
 'Unnamed: 198',
 'Unnamed: 199',
 'Unnamed: 200',
 'Unnamed: 201',
 'Unnamed: 202',
 '2020/01',
 '2020/01',
 'Unnamed: 205',
 'Unnamed: 206',
 'Unnamed: 207',
 'Unnamed: 208',
 'Unnamed: 209',
 '2020/02',
 '2020/02',
 'Unnamed: 212',
 'Unnamed: 213',
 'Unnamed: 214',
 'Unnamed: 215',
 'Unnamed: 216',
 '2020/03',
 '2020/03',
 'Unnamed: 219',
 'Unnamed: 220',
 'Unnamed: 221',
 'Unnamed: 222',
 'Unnamed: 223',
 '2020/05',
 '2020/05',
 'Unnamed: 226',
 'Unnamed: 227',
 'Unnamed: 228',
 'Unnamed: 229',
 'Unnamed: 230',
 '2020/06',
 '2020/06',
 'Unnamed: 233',
 'Unnamed: 234',
 'Unnamed: 235',
 'Unnamed: 236',
 'Unnamed: 237',
 '2020/07',
 '2020/07',
 'Unnamed: 240',
 'Unnamed: 241',
 'Unnamed: 242',
 'Unnamed: 243',
 'Unnamed: 244',
 '2020/08',
 '2020/08',
 'Unnamed: 247',
 'Unnamed: 248',
 'Unnamed: 249',
 'Unnamed: 250',
 'Unnamed: 251',
 '2020/09',
 '2020/09',
 'Unnamed: 254',
 'Unnamed: 255',
 'Unnamed: 256',
 'Unnamed: 257',
 'Unnamed: 258',
 '2020/10',
 '2020/10',
 'Unnamed: 261',
 'Unnamed: 262',
 'Unnamed: 263',
 'Unnamed: 264',
 'Unnamed: 265',
 '2020/11',
 '2020/11',
 'Unnamed: 268',
 'Unnamed: 269',
 'Unnamed: 270',
 'Unnamed: 271',
 'Unnamed: 272']